export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASLET";
export const REMOVE_ALL_ITEMS_FROM_BASKET = "REMOVE_ALL_ITEMS_FROM_BASKET";
export const UPDATE_QUANTITY = "UPDATE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";